function adjusted_sharpe_ratio{T}(Ra::TimeArray{T,1}) 
function appraisal_ratio{T}(Ra::TimeArray{T,1}, Rb::TimeArray{T,1}) 
function bernardo_ledoit_ratio{T}(Ra::TimeArray{T,1}) 
function calmar_ratio{T}(Ra::TimeArray{T,1}) 
function d_ratio{T}(Ra::TimeArray{T,1}) 
function kelly_ratio{T}(Ra::TimeArray{T,1}) 
function martin_ratio{T}(Ra::TimeArray{T,1}) 
function omega_sharpe_ratio{T}(Ra::TimeArray{T,1}) 
function pain_ratio{T}(Ra::TimeArray{T,1}) 
function prospect_ratio{T}(Ra::TimeArray{T,1}, mar=0) 
function sharpe_ratio{T}(Ra::TimeArray{T,1}, method::Function=std) 
function sharpe_ratio{T}(Ra::TimeArray{T,1}, method::Function=value_at_risk) 
function sharpe_ratio{T}(Ra::TimeArray{T,1}, method::Function=expected_shortfall) 
function skewness_kurtosis_ratio{T}(Ra::TimeArray{T,1})
function sortino_ratio{T}(Ra::TimeArray{T,1})
function treynor_ratio{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1}) 
function upside_potential_ratio{T}(Ra::TimeArray{T,1}) 
function hurst_index{T}(Ra::TimeArray{T,1})
function pain_index{T}(Ra::TimeArray{T,1})
function smoothing_index{T}(Ra::TimeArray{T,1}) 
function ulcer_index{T}(Ra::TimeArray{T,1}) 
function active_premium{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1}) 
function downside_deviation{T}(Ra::TimeArray{T,1})
function downside_frequency{T}(Ra::TimeArray{T,1})
function expected_shortfall{T}(Ra::TimeArray{T,1})
function fama_beta{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1}) 
function lower_partial_moment{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1}) 
function m2_sortina{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1})
function msquared{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1}) 
function msquared_excess{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1}) 
function modigliani{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1})
function max_drawdown{T}(Ra::TimeArray{T,1})
function mean_absolute_deviation{T}(Ra::TimeArray{T,1}) 
function net_selectivity{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1})
function omega{T}(Ra::TimeArray{T,1}) 
function selectivity{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1}) 
function semi_deviation{T}(Ra::TimeArray{T,1})
function specific_risk{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1})
function total_risk{T}(Ra::TimeArray{T,1},Rb::TimeArray{T,1})
function upside_frequency{T}(Ra::TimeArray{T,1}) 
function upside_risk{T}(Ra::TimeArray{T,1}) 
function value_at_risk{T}(Ra::TimeArray{T,1}) 
function volatility_skewness{T}(Ra::TimeArray{T,1}) 
